services:
  app:
    image: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
        build-args:
          BUILDKIT_INLINE_CACHE: "1"
        provenance: false
    ports:
      - "8000:8000"
    volumes:
      - ~/.aws:/root/.aws:ro
